apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configclients.spring.io
spec:
  preserveUnknownFields: false

  group: spring.io
  names:
    kind: ConfigClient
    listKind: ConfigClientList
    plural: configclients
    singular: configclient
  scope: "Namespaced"
  
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: ConfigClient is the Schema for the springs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ConfigClientSpec defines the desired state of ConfigClient
            properties:
              url:
                type: string
            type: object
          status:
            description: ConfigClientStatus defines the observed state of ConfigClient
            properties:
              complete:
                type: boolean
              observedGeneration:
                format: int64
                type: integer
            type: object
        type: object
    additionalPrinterColumns:
    - jsonPath: .spec.url
      description: config url
      name: URL
      type: string
    - jsonPath: .status.complete
      description: config status
      name: Complete
      type: boolean  
    subresources:
      status: {}  
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []